// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAitbojvGh3QTqEnU82QlRz-bU4t3Jrxys',
    appId: '1:1077221870341:web:8a7cce9eabad4907e6856c',
    messagingSenderId: '1077221870341',
    projectId: 'esp32flutter-f70c9',
    authDomain: 'esp32flutter-f70c9.firebaseapp.com',
    databaseURL: 'https://esp32flutter-f70c9-default-rtdb.firebaseio.com',
    storageBucket: 'esp32flutter-f70c9.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBalrD5Cb2xj4jhR4T1OmXlEcyOm9q3wZQ',
    appId: '1:1077221870341:android:e9215457a5ab9926e6856c',
    messagingSenderId: '1077221870341',
    projectId: 'esp32flutter-f70c9',
    databaseURL: 'https://esp32flutter-f70c9-default-rtdb.firebaseio.com',
    storageBucket: 'esp32flutter-f70c9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCkYFeDxJ_litgA_SYMDfW9YvzUCBQ4CEM',
    appId: '1:1077221870341:ios:fdca1aa7a6a2deffe6856c',
    messagingSenderId: '1077221870341',
    projectId: 'esp32flutter-f70c9',
    databaseURL: 'https://esp32flutter-f70c9-default-rtdb.firebaseio.com',
    storageBucket: 'esp32flutter-f70c9.appspot.com',
    iosClientId: '1077221870341-kpufiukcoqst38lqia21obren8ve7oop.apps.googleusercontent.com',
    iosBundleId: 'com.example.harv',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCkYFeDxJ_litgA_SYMDfW9YvzUCBQ4CEM',
    appId: '1:1077221870341:ios:fdca1aa7a6a2deffe6856c',
    messagingSenderId: '1077221870341',
    projectId: 'esp32flutter-f70c9',
    databaseURL: 'https://esp32flutter-f70c9-default-rtdb.firebaseio.com',
    storageBucket: 'esp32flutter-f70c9.appspot.com',
    iosClientId: '1077221870341-kpufiukcoqst38lqia21obren8ve7oop.apps.googleusercontent.com',
    iosBundleId: 'com.example.harv',
  );
}
